### ISSUE TITLE
How about compile-time SQL generation?

### ISSUE THREAD

**Issue by eminfedar** [jakin010/surrealdb_extra#1]
Very easy to use crate, thanks for that!

it seems everytime I call execute, it creates a SQL query string in runtime with push_str functions:
```rust
pub async fn execute(self, db: &Surreal<impl Connection>) -> Result<Response, QueryError> {

        let mut query = String::from("SELECT");

        if self.fields.0.contains(&"*".to_string()) {
            query.push_str(" *")
        } else {
            let fields_str = self.fields.0.join(",");

            query.push_str(&format!(" {}", fields_str))
        }

        if self.id.is_some() {
            query.push_str(" FROM type::thing($tb, $id)")
        } else {
            query.push_str(" FROM type::table($tb)");
        }

        if !self.filters.is_empty() {
            query.push_str(" WHERE");

            for filter in &self.filters {
                query.push_str(&format!(" {}", filter.to_string()))
            }
        }

        //... goes on
```

How about achieving this with macros and generate **SQL query in compile-time** and just fill the variables(if exist) in runtime with `format!()`?

Example, run-time version:
```rust
let query = Query::new().from("test", None).field("test").execute(&db).await.unwrap();
```
compile-time version
```rust
let var1 = 10;
let field1 = "runtimefield1";
let var2 = 20;

// macro syntax is just an example, not the main point
let query = sql!(
    table: "test",
    fields: "{field1}, field2",
    filters: "field1 = {var1} and field2 < {var2}",
    limit: 10
);
// this generates a SQL query string inside a format! macro:
//   format!(
//        "SELECT {field1}, field2 FROM test WHERE field1={var1}, field2={var2} LIMIT 10",
//        field1 = field1,
//        var1 = var1,
//        var2 = var2
//    );

// Send the sql to the database
db.query(query).await.unwrap();
```

But to be sure, these two approach must be benchmarked. I don't know if the cost of format!() can pass or not the ifs and  push_str()s approach. In theory it should be more performant.

Also if there are no {} dynamic fields in sql!() macro, then it can directly become a &'static str for queries like "SELECT * FROM person"

**Comment by alyti** [comment]
Using `format!` for a query is like asking for vulnerabilities in your application.

**Comment by jakin010** [comment]
Closing this issue the way the query builder is made/used has changed 

Changed to a better way waiting for the full release of beta.11 for now
