### ISSUE TITLE
sorry

### ISSUE THREAD

**Issue by frederik-uni** [jakin010/surrealdb_extra#5]
My crate has a similar name to yours. to be specific it's a 2 char difference. I just noticed when I tried looking it up on docs.rs. It's actually similar to your table feature. My crate is mostly automation for initialization and a wrapper for the default methods of surrealdb. I just wanted to say that it wasn't on purpose and apologize for it :D. 

Since I don't have a query builder in my crate I suggest that we could merge both crates.

**Comment by jakin010** [comment]
No problem no need to apologize. What do you want to merge?
